module.exports = {
	noText: [
		'CAADAgADdgIAAs7Y6AuS8Jc5tt8NrQI',
		'CAADAgADhQIAAs7Y6AsDUOoajJDBXAI',
		'CAADAgADvQIAAs7Y6As6LFazeoNA1AI',
		'CAADAgADbwIAAs7Y6AsOKNExV2UsIgI',
	],
	wait: [
		'CAADAgADZQIAAs7Y6Au1G24CTnsTpgI', 'CAADAgADiQIAAs7Y6AsqmlJHx13BTwI', 'CAADAgADmwIAAs7Y6As15Bk1QPu-cwI',
	],
	notFound: ['CAADAgADegIAAs7Y6AuR3bJUKSMqIgI'],
	error: ['CAADAgADiwIAAs7Y6AvQ3KEwyWpCwAI'],
}